config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'sessions/new'
  get 'users/new'
  get '/projects', to: 'static_pages#projects'
  get '/resume',   to: 'static_pages#resume'
  get '/signup',   to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/users', to: 'users#index'
  get '/edit', to: 'users#edit'
  patch '/edit', to: 'users#update'
  get '/profile', to: 'users#show'

  resources :users

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/photography', to: 'photography#index'
  get '/photography/add_photo', to: 'photography#new'
  post '/photography/add_photo', to: 'photography#create'
  delete '/photography/delete_photo', to: 'photography#destroy'
  patch '/photography/update_photo', to: 'photography#update'

  get '/photography/wedding', to: 'photography#wedding'

  resources :photography
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  VALID_PASSWORD_REGEX = /\A(?=.*[A-Z])(?=.*[!@#$&*])(?=.*[0-9])(?=.*[a-z]).{6,}\z/
  SPECIAL_CHAR_LIST = "!,@,#,$,&*"
  validates :password, presence: true, 
                       confirmation: { case_sensitive: false },
                       unless: Proc.new { |a| a.password.blank? },
                       format: { with: VALID_PASSWORD_REGEX, 
                                 message: "must contain upper, lower, number, and at least one #{SPECIAL_CHAR_LIST}." },
                       length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include UsersHelper
end

app/controllers/photography_controller.rb
class PhotographyController < ApplicationController

  def index

    @dropdown = ['None', 'Animals','Astrophotography','Portrait', 'General Session',
                 'Graduation', 'Landscapes', 'Travel', 'Sports', 'Cars']

    filter = params[:filter].to_s

    if ['Animals','Astrophotography','Portrait', 'General Session',
        'Graduation', 'Landscapes', 'Travel', 'Sports', 'Cars' ].include? filter
      filter = filter
    else
      filter = nil
    end

    if filter == nil || filter == "None"
      @photos = Photo.where("category != 'Engagement'").where("category != 'Wedding'").paginate(page: params[:page], per_page: 4).
          order('id DESC')
    else
      @photos = Photo.where("category != 'Engagement'").where("category != 'Wedding'").where("category = '#{filter}'")
                    .paginate(page: params[:page], per_page: 4).order('id DESC')
    end
  end

  def wedding
    @photos = Photo.where("category = 'Wedding'").paginate(page: params[:page], per_page: 50).order('id DESC')
  end

  def engagement

  end

  def new
    if logged_in? && admin?
      @photo = Photo.new
    else
      redirect_to root_path
      flash[:danger] = "More permissions required."
    end
  end

  def create
    if logged_in? && admin?
      @photo = Photo.new(photo_params)
      if @photo.save
        redirect_to photography_add_photo_path
        flash[:success] = "Photo added!"
      end
    end
  end

  def edit
    if logged_in? && admin?
      @photo = Photo.find(params[:id])
    else
      redirect_to root_path
      flash[:danger] = "More permissions required."
    end
  end

  def update
    if logged_in? && admin?
      @photo = Photo.find(params[:id])
      @photo.update(photo_params)
      redirect_to photography_path
      flash[:success] = "Photo updated!"
    else
      redirect_to root_path
      flash[:danger] = "More permissions required."
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def destroy
    if logged_in? && admin?
      @photo = Photo.find(params[:id])
      @photo.destroy
      redirect_to photography_path
      flash[:success] = "Photo deleted."
    end
  end

  private

  def admin?
    current_user.admin == true
  end

  def photo_params
    params.require(:photo).permit(:name, :link, :category, :description, :filter)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
      flash[:success] = "Log in successful."
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
    flash[:success] = "You have been logged out!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    counter = 1
    photo_list = []
    Photo.all.order('id DESC').where("category != 'Engagement'").where("category != 'Wedding'").each do |i|
      if counter <= 4
        photo_list.append(i.link)
        counter += 1
      end
    end
    @photo_show = photo_list
  end

  def projects
  end

  def resume
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :reg_user, only: [:show, :update, :edit]

  attr_accessor :name, :email

  def index
    if logged_in?
      if admin?
        @users = User.paginate(page: params[:page], per_page: 5)
      end
    else
      redirect_to root_path
    end
  end

  def show
    @user = current_user
  end

  def new
    if logged_in?
      if admin?
        @user = User.new
      else
        redirect_to current_user
        flash[:danger] = current_user.name + " ,you must be admin to create an account!"
      end
    else
      redirect_to root_path
      flash[:danger] = "Must be admin to create an account!"
    end
  end

  def create
    if admin?
      @user = User.new(users_params)
      if @user.save
        redirect_to root_path
        flash[:success] = "User created: " + @user.name
      else
        render 'new'
      end
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(edit_params)
    flash[:success] = "Profile updated!"
  end

  def destroy
    if admin?
      @user = User.find(params[:id])
      @user.destroy
      redirect_to users_path
      flash[:success] = @user.name + " has been deleted!"
    end
  end

  def admin?
    current_user.admin == true
  end

  private

  def reg_user
    current_user.admin == false
  end

  def users_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def edit_params
    params.require(:user).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis
  def full_title(page_title = '')
    base_title = "np.com"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/photography_helper.rb
module PhotographyHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper




end

app/views/layouts/_about_modal.html.erb
<div class="w3-modal-content w3-card-2 w3-animate-top">
  <header class="w3-container w3-theme-l1 w3-black">
        <span onclick="document.getElementById('id01').style.display='none';w3_open()"
              class="w3-button w3-display-topright">×</span>
    <h4>ABOUT</h4>
  </header>
  <div id="about_modal" class="w3-padding">
    <h4>Website Specs:</h4>
    <ul>
      <li><a href="https://rubyonrails.org/" target="_blank">Ruby: 2.5.x</a></li>
      <li><a href="https://rubyonrails.org/" target="_blank">Rails: 5.2.x</a></li>
    </ul>
    <h4>Layout Libraries</h4>
    <ul>
      <li><a href="http://getbootstrap.com/" target="_blank">Bootstrap</a></li>
      <li><a href="https://fontawesome.com/" target="_blank">Font-Awesome</a></li>
      <li><a href="https://www.w3schools.com/default.asp" target="_blank">W3-Schools</a></li>
    </ul>
  </div>
  <footer class="w3-container w3-theme-l1 w3-black">
    <p>Welcome to NathanielPautzke.com</p>
  </footer>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer w3-container w3-center w3-margin-top">
  <p>Find me on social media.</p>
  <a target="_blank" rel="noopener noreferrer" href="https://www.facebook.com/NathanielPautzkePhotography/"><i class="fa fa-facebook-official w3-hover-opacity"></i></a>
  <a target="_blank" rel="noopener noreferrer" href="https://www.instagram.com/nathaniellpautzke/"><i class="fa fa-instagram w3-hover-opacity"></i></a>
  <a target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/in/nathaniel-pautzke"><i class="fa fa-linkedin w3-hover-opacity"></i></a>
  <p>Welcome to nathanielpautzke.com</p>
</footer>

app/views/layouts/_header.html.erb
<div class="w3-top">
  <!-- Header Logo and Links --> 
  <div class="w3-bar w3-black w3-wide w3-padding w3-card">
    <% if request.original_url != root_url %>
      <%= link_to image_tag('navbar/lighthouse.png'), root_path, id: "logo"%>
    <% else %>
      <%= image_tag('navbar/lighthouse.png', id: "logo") %>
    <% end %>
    <div class="w3-button w3-right" onclick="w3_open()">☰</div>

    <% if logged_in? %>
      <%= link_to "Log out", logout_path, method: :delete, class: "w3-button w3-right" %>
      <% else  %>
      <%= link_to "Log in", login_path, class: "w3-button w3-right"  %>
    <% end %>

  </div>

  <!-- Pop out sidebar -->
  <div class="w3-sidebar w3-bar-block w3-card w3-top w3-animate-right w3-black"
       style="color:white;display:none;z-index:2;right:0px;width:200px;min-width:250px;" id="mySidebar">
    <%= render 'layouts/sidebar' %>
  </div>
</div>

<!-- About Modal -->
<div id="id01" class="w3-modal">
  <%= render 'layouts/about_modal' %>
</div>

app/views/layouts/_login_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>

  <%= f.label :email %>
  <%= f.text_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.submit "Create my account", class: "btn btn-primary" %>
  <a href="<%= root_url %>" class="btn btn-primary w3-right">Cancel</a>
<% end %>

app/views/layouts/_sidebar.html.erb
<a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button nav-font-large "><i class="fa fa-times-circle" style="padding-right: 5px;"></i>Close Menu</a>
<% if request.original_url != root_url %>
<a href="/" onclick="w3_close()" class="w3-bar-item w3-button nav-font-large"><i class="fa fa-home" style="padding-right: 5px"></i> Home</a>
<% end %>
<a href="<%= photography_url %>" onclick="w3_close()" class="w3-bar-item w3-button nav-font-large"><i class="fa fa-camera-retro" style="padding-right: 5px"></i> Photography</a>
<a href="<%= projects_url %>" onclick="w3_close()" class="w3-bar-item w3-button nav-font-large"><i class="fa fa-desktop" style="padding-right: 5px"></i>Projects</a>
<a href="<%= resume_url %>" onclick="w3_close()" class="w3-bar-item w3-button nav-font-large"><i class="fa fa-mortar-board" style="padding-right: 5px"></i>Resume</a>

<% if logged_in? %>
<div class="w3-padding-16">
  <a href="<%= profile_url %>" class="w3-btn w3-large w3-dark-grey w3-hover-light-grey" style="font-size: large;">Profile</a>
</div>
  <% if current_user.admin? %>
    <div class="w3-padding-16">
      <%= link_to "Sign up", signup_path, class: "w3-btn w3-large w3-dark-grey w3-hover-light-grey", style: "font-size: large;" %>
    </div>
    <div class="w3-padding-16">
      <a href="<%= users_url %>" class="w3-btn w3-large w3-dark-grey w3-hover-light-grey" style="font-size: large;">Users</a>
    </div>
    <div class="w3-padding-16">
      <a href="<%= photography_add_photo_url %>" class="w3-btn w3-large w3-dark-grey w3-hover-light-grey" style="font-size: large;">Add Photos</a>
    </div>
  <% end %>
<% end %>

<div class="w3-padding-16">
  <a class="w3-btn w3-large w3-dark-grey w3-hover-light-grey"
     onclick="document.getElementById('id01').style.display='block';w3_close()"
     style="font-size: large;">ABOUT
  </a>
</div>

app/views/layouts/_sign_up.html.erb
<%= form_for(@user, url: signup_path) do |f| %>
  <%= render 'shared/error_messages' %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.text_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit "Create my account", class: "btn btn-primary" %>
  <a href="<%= root_path %>" class="btn btn-primary w3-right" id="signup-cancel">Cancel</a>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag "favicon.ico" %>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-129383298-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-129383298-1');
    </script>

  </head>
  <body>

    <%= render 'layouts/header' %>

    <% flash.each do |message_type, message| %>
       <div id="flash-box" class="w3-animate-top alert alert-<%= message_type %>"><%= message %>
         <i class="w3-right fa fa-window-close"
            style="padding-top:4px;" onclick="flash_close()"></i>
       </div>
    <% end %>

    <div class="container" >
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>

  </body>

  <!-- Ruby debug box for development -->
  <%= debug(params) if Rails.env.development? %>
</html>

app/views/photography/edit.html.erb
<%= form_for @photo, url: "/photography/#{@photo.id}"  do |f| %>
  <%#= render 'shared/error_messages' %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :link %>
  <%= f.text_field :link, class: 'form-control' %>

  <%= f.label :category %>
  <br/>
  <%= f.select :category, ['Animals','Astrophotography','Wedding', 'Engagement','Portrait', 'General Session',
                           'Graduation', 'Landscapes', 'Travel', 'Sports', 'Cars' ], class: 'form-control' %>
  <br/>

  <%= f.label :description %>
  <%= f.text_area :description, class: 'form-control' %>


  <%= f.submit "Update", class: "btn btn-primary" %>
  <a href="<%= root_path %>" class="btn btn-primary w3-right" id="signup-cancel">Cancel</a>
<% end %>

app/views/photography/index.html.erb
<% provide(:title, "Photography") %>

<div>
  <a href="<%= photography_wedding_url %>"><button class="w3-blue">Wedding Photos</button></a>
</div>

<div class="w3-dropdown-hover" style="margin-left: 15px;margin-bottom: 5px;">
  <button class="w3-button w3-theme">Filter Images <i class="fa fa-caret-down"></i></button>
  <div class="w3-dropdown-content w3-bar-block w3-border">
    <% @dropdown.each do |item| %>
    <a href="<%= photography_url %>?filter=<%= item %>" class="w3-bar-item w3-button"><%= item %></a>
    <% end %>
</div>
</div>


<div class="w3-row w3-row-padding" style="margin-bottom:25px">
  <% if @photos.empty? %>
    <p>Images have not been added for this category yet. Check back soon!</p>
    <% else %>
  <% @photos.each do |photo| %>
    <div class="w3-half">
      <img src="<%= photo.link %>" style="width:100%" alt="<%= photo.name %>">
        <%= link_to "View Photo", "photography/#{photo.id}", method: :get %>
        <% if logged_in?  %>
          <% if current_user.admin?  %>
           <%= link_to "Delete", "photography/#{photo.id}", method: :delete %>
          <% end %>
        <% end %>
    </div>
    <% end %>
  <% end %>
</div>

<%= will_paginate @photos %>

app/views/photography/new.html.erb
<%= provide(:title, "Add Photo") %>

<%= form_for(@photo, url: photography_add_photo_url) do |f| %>
  <%#= render 'shared/error_messages' %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :link %>
  <%= f.text_field :link, class: 'form-control' %>

  <%= f.label :category %>
  <br/>
  <%= f.select :category, ['Animals','Astrophotography', 'Wedding', 'Engagement','Portrait', 'General Session',
                           'Graduation', 'Landscapes', 'Travel', 'Sports', 'Cars' ], class: 'form-control' %>
  <br/>

  <%= f.label :description %>
  <%= f.text_area :description, class: 'form-control' %>


  <%= f.submit "Submit Photo", class: "btn btn-primary" %>
  <a href="<%= root_path %>" class="btn btn-primary w3-right" id="signup-cancel">Cancel</a>
<% end %>

app/views/photography/show.html.erb
<%= provide(:title, "#{@photo.name}") %>

<div class="w3-card w3-round w3-white">
  <div class="w3-container">
    <h4 class="w3-center"><%= @photo.name %></h4>
    <p class="w3-center"><img src="<%= @photo.link %>" style="width: 80%" alt="<%= @photo.name %>"></p>
    <hr>
    <p><i class="fa fa-chevron-right fa-fw w3-margin-right w3-text-theme"></i><b>Category:</b> <%= @photo.category %></p>
    <p><i class="fa fa-chevron-right fa-fw w3-margin-right w3-text-theme"></i><b>Description:</b> <%= @photo.description %></p>
  </div>
  <% if request.env['HTTP_REFERER'].to_s.include? "/photography" %>
      <%= link_to "Back to Photos", request.env['HTTP_REFERER'], fallback_location: photography_path, class: "btn btn-primary", style: "margin: 5px" %>
    <% else %>
    <%= link_to "Back to Photos", photography_path, class: "btn btn-primary", style: "margin: 5px" %>
    <% end %>
  <% if logged_in?  %>
    <% if current_user.admin? %>
     <%= link_to "Edit Photo", edit_photography_path, class: "btn btn-primary", style: "margin: 5px" %>
      <% end %>
  <% end %>
</div>

app/views/photography/wedding.html.erb
<%= provide(:title, "Wedding") %>

<h2>Weddings</h2>
<hr/>
<div id="myGrid" class="w3-container w3-center">
  <!-- Photo Grid -->
  <div >
    <% @photos.each do |images| %>
      <div>
        <%= image_tag images.link, class: "grid-item" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% unless !@user.errors.any? %>
<div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%=  pluralize(@user.errors.count, "error")  %>.
      </div>
  <ul>
    <%  @user.errors.full_messages.each do |msg|  %>
    <li style="color: red;"><%=  msg  %></li>
    <%  end  %>
  </ul>
</div>
<%  end %>

app/views/static_pages/home.html.haml
= provide(:title, "Home")
%body
  .w3-container.w3-row-padding.w3-center
    .w3-third
      .w3-card.w3-container{:style => "min-height:410px"}
        %h3 Photography
        %br/
        %i.fa.fa-camera-retro.w3-margin-bottom.w3-text-theme{:style => "font-size:120px"}
        %p Meaningful Sessions
        %p High Quality
        %p Reasonably Priced
    .w3-third
      .w3-card.w3-container{:style => "min-height:410px"}
        %h3 Software Engineer
        %br/
        %i.fa.fa-database.w3-margin-bottom.w3-text-theme{:style => "font-size:120px"}
        %p Language Driven
        %p Best Practices Focused
        %p Passionate
    .w3-third
      .w3-card.w3-container{:style => "min-height:410px"}
        %h3 Creative Thinker
        %br/
        %i.fa.fa-lightbulb-o.w3-margin-bottom.w3-text-theme{:style => "font-size:120px"}
        %p Idea Motivated
        %p Innovative
        %p Quick Learner

  -#.w3-container.w3-card.w3-margin-top{:style => "background-color:#D3D3D3D3"}
  %h3.w3-center.w3-margin-top Spotlight Photos
  %hr
  .w3-container.w3-content{:style => "max-width:900px;position:relative"}
    - @photo_show.each do |link|
      %img.mySlides{:src => "#{link}", :style => "width:100%"}/
  %hr

  .w3-container.w3-black.w3-center.w3-opacity.w3-padding-32.w3-margin-top
    %h1.w3-margin.w3-xlarge
      %i.fa.fa-quote-left
        Computer science is no more about computers than astronomy is about telescopes.
      %i.fa.fa-quote-right
      %br
        Edsger Dijkstra
  .w3-half.w3-blue-grey.w3-container.w3-margin-top{id: "mission"}
    .w3-padding-64.w3-center
      %h1 About Me
      %i.fa.fa-user-circle-o.w3-margin-bottom.w3-text-theme{:style => "font-size:50px"}
      .w3-left-align.w3-padding-large
        %p
          Software Engineer and hobby photographer from Shorewood Minnesota. One reason I wanted to become a software
          engineer is that I love seeing an idea come to life.
        %p
          Also, I enjoy problem-solving in general. There is something
          about working on a complex problem and you finally get that “ah-ha” moment. There is no better feeling.
  .w3-half.w3-container.w3-margin-top{id: "mission",:style => "background-color:#D3D3D3D3"}
    .w3-padding-64.w3-center
      %h1 Mission
      %i.fa.fa-balance-scale.w3-margin-bottom.w3-text-theme{:style => "font-size:50px"}
      .w3-left-align.w3-padding-large
        %p
          My mission is to focus on quality and innovation in any aspect of my life. I enjoy learning and strive to
          succeed as the little fish in the big pond.
        %p
          I operate with integrity and intention with a goal driven attitude. My personal philosophy is that
          one is never done learning.
  :javascript
    slideShow();

app/views/static_pages/projects.html.haml
= provide(:title, "Projects")

.w3-container
  %h1
    My Projects
  %br
  .w3-card-4{:style => "max-width:1400px"}
    %header.w3-container.w3-light-grey
      %h3 NathanielPautzke.com
    .w3-container.w3-padding-16
      %p
        Framework: Rails | Language: Ruby
        %br
        Deployment Strategy: Heroku Box with custom domain
      %hr/
      %img.w3-left.w3-margin-right{:alt => "Avatar", :src => image_path("navbar/lighthouse.png"), :style => "width:100px"}/
      %p
        With the experience I gained from working at my first job as a developer, I found a love for Ruby on Rails. The
        idea of convention over configuration was an interesting concept to grasp early on, but now really enjoy the
        framework. The purpose of this site is to give me a personal space outside of social media where I can show other
        parts of my life such as photography, work experience, and hopefully more to come.
      %p
        This project was developed on a Linux box using the RubyMine IDE. Purchasing my own domain, I was able to
        map my Heroku DNS to my custom domain name that also includes security certificates.  Dev tracking software and Git was used
        to develop the website and push to a production server. This app is hosted on nathanielpautzke.com and if you like my
        workd head over to my
        = link_to "resume", resume_path, :style => "color: blue"
        page.
  %br
  .w3-card-4{:style => "max-width:1400px"}
    %header.w3-container.w3-light-grey
      %h3
        My Wedding Website:
        = link_to "wedding.mollyandnathaniel.com", "https://wedding.mollyandnathaniel.com", :style => "color:blue", :target => "_blank"
    .w3-container.w3-padding-16
      %p
      Framework: ASP.NET Core | Language: C#
      %br
      Deployment Strategy: Digital Ocean Droplet/Nginx/CertBot(ssl)
      %hr/
      %p
        When we were planning our wedding, I wanted to have the option to have people come and give us any photos that
        they had taken that day. The idea was similar to the disposable camera that people left after the wedding was over. Getting
        started with this project, I knew I needed some help. I teamed up with my best friend. He was not a fan of rails
        and used ASP.NET a lot. I learned C# and ASP.Net as well as nginx and cert bot to deploy to digital ocean. I tried
        to keep cost minimal but had enough resources to get through the wedding day. We also created an admin portal to approve or
        deny photos being displayed on the website. It was a success with more than 100 users on the website as well as 20+
        submissions.

app/views/users/index.html.haml
= provide(:title, "Users")

%body
  %h2
    = @users.count
    users
    %hr/
  = will_paginate
    - @users.each do |user|
    / Users
    - if !user.admin?
      .w3-container.row.w3-round.w3-white{ style: "margin-top: 10px;"}
        .w3-container.w3-card.col-md-6.col-md-offset-3
          %p
            %i.fa.fa-pencil.fa-fw.w3-margin-right.w3-text-theme
            Email:
            = user.email
          %hr/
          %p
            %i.fa.fa-pencil.fa-fw.w3-margin-right.w3-text-theme
            Name:
            = user.name
          %p
            %i.fa.fa-pencil.fa-fw.w3-margin-right.w3-text-theme
            Bio:
          %hr/
          = link_to "Delete", user_path(user), method: :delete, data: { confrim: 'Are you sure?'}

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>

  <div class="row">
  <div class="col-md-6 col-md-offset-3">
  <h1>Sign Up</h1>
  <p>This form is reserved for admin purposes only.</p>
  <hr>

  <%= render 'layouts/sign_up' %>

    </div>
  </div>